### ISSUE TITLE
no scrollbars when docked

### ISSUE THREAD

**Issue by mishaxz** [odalet/VSWebBrowserExtension#5]
I am docking it to the bottom in VS.. there are no scrollbars.. When floating there are scrollbars.

For reference I am using www.you.com

**Comment by odalet** [comment]
I've tested a bit:

* Open Web Browser -> appears as a document
* Browse to www.you.com -> scrollbars ok
* Move the window and dock it to the bottom -> scrollbars still ok
* Go to Options and set www.you.com as the home page
* Close Visual Studio
* Open it again
* Web Browser is still docked at the bottom, you.com is browsed to and scrollbars are here...

![image](https://user-images.githubusercontent.com/79333/217476736-473bc82e-e1b2-4a97-a824-13659b137c9e.png)

I'm sorry, but I can't seem to reproduce your issue.

What (exact) version of Visual Studio do you use? Can you describe reproduction steps?
